name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  dart_define: ^1.0.1



flutter:
  uses-material-design: true

dart_define:
  dart: true # OPTIONAL: Whether to generate the dart boilerplate or not. Defaults to true
  json: true # OPTIONAL: Whether to generate the json boilerplate or not. Defaults to true
  json_path: dart_define.json # OPTIONAL: The path to the json file to generate. Defaults to dart_define.json
  dart_path: lib/dart_define.gen.dart # OPTIONAL: The path to the dart file to generate. Defaults to lib/dart_define.gen.dart
  class_name: dart_define # OPTIONAL: The name of the generated class. Defaults to dart_define

  variables: # The variables to add to the generated config files
    - name: STRING_VALUE # REQUIRED: The name of the variable
      description: An example String value # REQUIRED: The description of the variable
      default: hello world! # REQUIRED: If `required` is false, this field is mandatory. Otherwise, it is ignored.
      required: false # OPTIONAL: If this is set to true, the CLI tool will throw an exception if the variable is not provided as an argument. Defaults to true.
    - name: INT_VALUE
      description: An example int value
      default: 3
      required: false
    - name: BOOL_VALUE
      description: An example bool value
      required: true
  flavors: # OPTIONAL: The flavors to use within the app
    - name: production # REQUIRED: The name of the flavor
      description: The production flavor # REQUIRED: The description of the flavor
    - name: staging
      description: The staging flavor
    - name: development
      description: The development flavor
