name: dart_define
description: Utility for generating and populating dart-define config files
version: 2.0.1
homepage: https://mankeli.co
repository: https://github.com/Mankeli-Software/dart_define

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  args: ^2.4.1
  checked_yaml: ^2.0.3
  cli_completion: ^0.3.0
  cmd_plus: ^1.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  mankeli_core: ^0.0.5
  mustache_template: ^2.0.0
  path: ^1.8.3
  pub_updater: ^0.3.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  dart_code_metrics: ^5.7.5
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  mankeli_analysis: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2

executables:
  dart_define:

scripts:
  gen:
    code: flutter pub run build_runner build --delete-conflicting-outputs

