name: dart_define
description: Utility for generating and populating dart-define config files
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.1
  change_case: ^1.1.0
  checked_yaml: ^2.0.3
  cli_completion: ^0.3.0
  cmd_plus: ^1.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  mustache_template: ^2.0.0
  path: ^1.8.3
  pub_updater: ^0.2.4
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  mankeli_analysis: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2

executables:
  dart_define:

scripts:
  gen:
    code: flutter pub run build_runner build --delete-conflicting-outputs

dart_define:
  dart: true # Whether to generate the dart boilerplate or not. Defaults to true
  json: true # Whether to generate the json boilerplate or not. Defaults to true
  variables: # The variables to add to the generated config files
    - name: string_value # REQUIRED: The name of the variable
      description: An example String value # REQUIRED: The description of the variable
      default: hello world! # REQUIRED: If `required` is false, this field is mandatory. Otherwise, it is ignored.
      required: false # OPTIONAL: If this is set to true, the CLI tool will throw an exception if the variable is not provided as an argument. Defaults to true.
    - name: int_value
      description: An example int value
      default: 3
      required: false
    - name: bool_value
      description: An example bool value
      required: true
