name: dart_define
description: Utility for generating and populating dart-define config files
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.1
  cli_completion: ^0.3.0
  cmd_plus: ^1.3.2
  pub_updater: ^0.2.4


dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mankeli_analysis: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2

executables:
  dart_define:
