// This file was generated by package:dart_define, DO NOT modify or remove these comments
class DartDefine {
  /// An example String value
  static const stringValue = String.fromEnvironment('string_value');

  /// An example int value
  static const intValue = int.fromEnvironment('int_value');

  /// An example bool value
  static const boolValue = bool.fromEnvironment('bool_value');
}
