// This file was generated by package:dart_define, DO NOT modify or remove these comments
class DartDefine {
  DartDefine._();

  /// An example String value
  static const stringValue = String.fromEnvironment('STRING_VALUE');

  /// An example int value
  static const intValue = int.fromEnvironment('INT_VALUE');

  /// An example bool value
  static const boolValue = bool.fromEnvironment('BOOL_VALUE');
}
