name: '[CI]'

on:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.5
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs
        
      - name: Verify formatting
        run: dart format . --fix

      - name: Analyze project source
        run: flutter analyze . --fatal-infos --no-pub

      - name: Run tests
        run: flutter test --no-pub

      - uses: EndBug/add-and-commit@v9
        with:
          message: Formats code
          committer_name: GitHub Actions
          committer_email: actions@github.com
